### ISSUE TITLE
Think there is a problem with the code

### ISSUE THREAD

**Issue by sailuluo** [tristandb/EfficientDet-PyTorch#1]
In model.py,line 203:
   self.fpn = [PyramidFeatures(fpn_sizes, feature_size=feature_size, index=index).cuda() for index in range(max(2+phi, 8))]

a little problem with the repeat time of BiFPN. I think ‘max’ should change to ‘min’.

**Comment by tristandb** [comment]
Thats indeed correct. I'll update the code.
