### ISSUE TITLE
About the implementation of FastFusion

### ISSUE THREAD

**Issue by kaishian** [tristandb/EfficientDet-PyTorch#3]
Hi @tristandb Thank you for your excellent work!

About the "Top-Down Pathway":
p3_td = self.p3_td(w1[0, 3] * p3_x + w1[1, 3] * F.interpolate(p4_x, scale_factor=2))

I think <p3_td> is created by <p4_td> and <p3_x>, do you agree?
p3_td = self.p3_td(w1[0, 3] * p3_x + w1[1, 3] * F.interpolate(p4_td, scale_factor=2))

About the "Bottom-Up Pathway":
<p7_out> shall be created by <p7_x> and <p6_out>

**Comment by yrd241** [comment]
I really think you are correct.
Based on the original paper, I think not only the p3_td should be created by p4_td and p3_x, but p4_td, p5_td also needed to be created by p*+1_td and p*_x.

**Comment by tristandb** [comment]
Thanks for reaching out! You're correct. I'll update the code as soon as possible.

**Comment by alicera** [comment]
Top-Down ：use  the  F.interpolate
Bottom-Up : use the  nn.Upsample

What is the different from interpolate and Upsample?
Only use the F.interpolate, is it better?
Only use the  nn.Upsample , is it better?
